
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iot?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root